= MIDIUSB Library for Arduino =

With minor adjustments by zenpho

The original MIDI library is based on PluggableUSB (so is only compatible with Arduino IDE 1.6.6 and newer) allows an Arduino board with USB capabilities to act as a MIDI instrument over USB.

Minor adjustments here are to configure multiple JACKS (confusingly sometimes called CABLES or PORTS) such that several parallel data streams may be transmitted to several physical MIDI devices by USART.

== License ==

Copyright (c) 2015, Arduino LLC. All right reserved.
Copyright (c) 2015, Gary Grewal

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
